In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

file_data = []

f = open("./train.txt", "r")
file_data += f.readlines()
f.close()

f = open("./valid.txt", "r")
file_data += f.readlines()
f.close()

f = open("./test.txt", "r")
file_data += f.readlines()
f.close()

file_df = pd.DataFrame(file_data).iloc[:,0].str.split('\t', expand=True).set_axis(["CATEGORY", "TITLE"], axis=1)

vectorizer = TfidfVectorizer(min_df=10)
features = vectorizer.fit_transform(file_df["TITLE"])
feature_names = vectorizer.get_feature_names_out()

feature_df = pd.DataFrame(features.toarray(), columns=feature_names, index=file_df.index).fillna(0)

df = pd.concat([file_df, feature_df], axis=1)
df

,CATEGORY,TITLE,10,100,11,12,13,1300,14,15,...,yields,york,you,young,your,yr,yuan,zac,zendaya,zone
0,m,UPDATE 1-Guinea haemorrhagic fever may have cr...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,b,France's Orange won't carry Netflix on set-top...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,b,"UPDATE 3-Valeant shares fall on lowered 2014, ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,e,Dylan fan shells out $2MILLION for one-of-a-ki...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,b,UPDATE 6-France meets Alstom bidders with pled...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13350,m,EMT punished after video surfaces of him 'vogu...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13351,m,AstraZeneca Cancer News Boosts Soriot's $45 Bi...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13352,b,Lennar Quarterly Profit Beats Estimates as US ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13353,e,Harrison Ford - Star Wars cast announced\n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13354,e,Avril Lavigne - Avril Lavigne's Hello Kitty Vi...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
data_size = df.shape[0]
train_max_idx = int(data_size * 0.80)
valid_max_idx = int((data_size - train_max_idx) * 0.50) + train_max_idx

In [3]:
train_df = df.iloc[:train_max_idx]
valid_df = df.iloc[train_max_idx:valid_max_idx]
test_df  = df.iloc[valid_max_idx:-1]

In [4]:
train_df.to_csv("./train.feature.txt", index=False)
valid_df.to_csv("./valid.feature.txt", index=False)
test_df.to_csv("./test.feature.txt", index=False)